/* Copyright 2026 by John A Kline.  See LICENSE.txt for your rights.

   The sample report's page behavior, and only three things: the Hourly
   page's day tabs, the chart crosshair, and the alert strings whose text
   depends on what time it is now.

   THIS PAGE DOES NOT RELOAD ITSELF.  It fetches nothing and polls nothing --
   the report is regenerated by WeeWX on its own cycle, and an auto-reloading
   sample would be an opinion imposed on everyone who copies this skin.  What
   the clock pass below does is re-render values ALREADY IN THE MARKUP: an
   alert's badge, its countdown and its window bar are written by
   bin/user/nwsskin.py at generation time and would otherwise drift as the
   minutes pass on a tab left open.  No network, no state, no storage.

   Every block self-guards, so a page with no charts, no tabs or no alerts
   simply skips that part.  Nothing here is required for the page to be
   readable: with javascript off, the first paint is already correct and the
   Hourly page shows its first day. */

(function () {
  'use strict';

  var MINUTE = 60000;

  /* Whether the last thing the reader did was type.  :focus-visible ought to
     answer this, but the engines disagree about an SVG: Chromium matches it
     after a plain mouse CLICK and Firefox does not, so the focus ring appeared
     round the whole chart in one browser and nowhere in the other.  Tracking
     the modality ourselves is deterministic in both.  Capture phase, so it is
     recorded before any handler that might move focus. */
  var typing = false;
  document.addEventListener('keydown', function () { typing = true; }, true);
  document.addEventListener('pointerdown', function () { typing = false; }, true);

  /* ---- relative time -------------------------------------------------
     This ladder must agree EXACTLY with NWSSkin.fuzzy() in
     bin/user/nwsskin.py, which writes the same strings at generation time.
     Math.round is why that function rounds half UP rather than using
     python's round(), which rounds half to even. */

  function fuzzy(seconds) {
    var s = Math.abs(seconds);
    var n, unit;
    if (s < 3600) {
      n = Math.round(s / 60); unit = 'minute';
    } else if (s < 86400 * 2) {
      n = Math.round(s / 3600); unit = 'hour';
    } else {
      n = Math.round(s / 86400); unit = 'day';
    }
    return n + ' ' + unit + (n === 1 ? '' : 's');
  }

  function setText(el, text) {
    /* Guarded write: never assume the element is there, and never write
       undefined into the page. */
    if (el && text !== undefined && text !== null) { el.textContent = text; }
  }

  /* ---- the clock pass ------------------------------------------------ */

  function plural(n, word) {
    return n + ' ' + word + (n === 1 ? '' : 's');
  }

  /* The count line states how many alerts are IN EFFECT, which is a fact
     about the clock, so it goes stale exactly like the badges do.  It is
     baked by NWSSkin.count_line() at generation and rewritten here from the
     cards' own recomputed state -- otherwise the page can head three cards
     with "3 alerts in effect" while the first of them reads EXPIRED.  The
     wording must match count_line(), which
     TestCountLine.test_the_page_script_carries_the_same_wording pins. */
  function tickCount(active, later, total) {
    var el = document.querySelector('.acountline');
    if (!el) { return; }
    if (active && later) {
      el.innerHTML = '<b>' + plural(active, 'alert') + '</b> in effect now, <b>'
        + plural(later, 'alert') + '</b> beginning later \u2014 in effect first, '
        + 'then most serious first.';
    } else if (active) {
      el.innerHTML = '<b>' + plural(active, 'alert')
        + '</b> in effect \u2014 most serious first.';
    } else if (later) {
      el.innerHTML = '<b>' + plural(later, 'alert') + '</b> not yet begun.';
    } else {
      el.innerHTML = '<b>' + plural(total, 'alert') + '</b> \u2014 none in effect now.';
    }
  }

  function tickAlerts(now) {
    /* An alert's badge, note and window bar all depend on the clock.  An
       alert with no end time uses expires; one with neither gets no bar.
       An open-ended alert is one with NO data-ends attribute -- nwsskin.py
       omits it deliberately, so its absence is the signal, not an oversight. */
    /* `.alert`, NOT `.alert[data-onset]`.  NWS does not always give an onset,
       and nwsskin.py writes no data-onset when it is absent -- so the narrower
       selector silently skipped exactly the cards whose state is hardest to
       get right, leaving them frozen at whatever generation baked. */
    var cards = document.querySelectorAll('.alert');
    var activeCount = 0, laterCount = 0;
    for (var i = 0; i < cards.length; i++) {
      var card = cards[i];
      var onset = parseInt(card.getAttribute('data-onset'), 10);
      var ends = parseInt(card.getAttribute('data-ends'), 10);
      var expires = parseInt(card.getAttribute('data-expires'), 10);
      var finish = isNaN(ends) ? expires : ends;
      var openEnded = isNaN(ends);
      var badge = card.querySelector('.badge');
      var note = card.querySelector('.anote');
      /* The three rules NWSForecastVariables.alert_state() states, spelled
         the way that file says to spell them.  `ended` tests FINISH, not
         "started and not active": an alert with no onset whose window has
         closed is ended, and the obvious spelling files it as upcoming. */
      var started = !isNaN(onset) && onset <= now;
      var active = started && (isNaN(finish) || now <= finish);
      var state = active ? 'active'
                : ((!isNaN(finish) && now > finish) ? 'ended' : 'upcoming');
      if (state === 'active') { activeCount++; }
      else if (state === 'upcoming') { laterCount++; }

      if (badge) {
        badge.className = 'badge ' + (state === 'active' ? 'on'
                                    : (state === 'ended' ? 'past' : 'soon'));
        setText(badge, state === 'active' ? 'In effect now'
                : (state === 'ended' ? 'Expired'
                   : (isNaN(onset) ? 'Not yet begun'
                      : 'Begins in ' + fuzzy(onset - now))));
      }
      if (note) {
        if (active && openEnded && !isNaN(expires)) {
          setText(note, 'no end time given · next update in ' + fuzzy(expires - now));
        } else if (active && !isNaN(finish)) {
          setText(note, 'ends in ' + fuzzy(finish - now));
        } else if (state === 'upcoming' && !isNaN(finish)) {
          setText(note, 'runs to ' + note.getAttribute('data-ends-text'));
        } else if (state === 'ended' && !isNaN(finish)) {
          setText(note, 'ended ' + fuzzy(finish - now) + ' ago');
        }
      }
      var fill = card.querySelector('.aw-fill');
      var mark = card.querySelector('.aw-now');
      if (fill && mark && !isNaN(onset) && !isNaN(finish) && finish > onset) {
        var frac = Math.min(Math.max((now - onset) / (finish - onset), 0), 1) * 100;
        fill.style.width = frac + '%';
        mark.style.left = frac + '%';
      }
    }
    if (cards.length) { tickCount(activeCount, laterCount, cards.length); }
  }

  function tick() {
    tickAlerts(Math.floor(Date.now() / 1000));
  }

  /* ---- day tabs ------------------------------------------------------ */

  function wireTabs() {
    var tabs = document.querySelectorAll('.daytab[data-day]');
    var panes = document.querySelectorAll('.daypane[data-day]');
    if (!tabs.length) { return; }
    function show(day) {
      var i;
      for (i = 0; i < tabs.length; i++) {
        tabs[i].classList.toggle('on', tabs[i].getAttribute('data-day') === day);
      }
      for (i = 0; i < panes.length; i++) {
        panes[i].classList.toggle('off', panes[i].getAttribute('data-day') !== day);
      }
    }
    for (var t = 0; t < tabs.length; t++) {
      tabs[t].addEventListener('click', function () {
        show(this.getAttribute('data-day'));
      });
    }
  }

  /* ---- chart crosshair ----------------------------------------------- */

  function wireChart(svg) {
    var spec;
    try {
      spec = JSON.parse(svg.getAttribute('data-chart'));
    } catch (e) {
      return;                        /* one bad chart must not kill the page */
    }
    if (!spec || !spec.p || !spec.p.length) { return; }

    var cross = svg.querySelector('.cross');
    var line = svg.querySelector('.cx');
    var dotT = svg.querySelector('.cdot');
    var dotD = svg.querySelector('.cdotd');
    var out = svg.parentNode ? svg.parentNode.querySelector('.readout') : null;
    if (!cross || !line || !dotT || !dotD || !out) { return; }

    var n = spec.p.length;
    var step = n > 1 ? (spec.x1 - spec.x0) / (n - 1) : 1;

    function yFor(v) {
      return spec.y1 - (spec.y1 - spec.y0) * (v - spec.lo) / spec.span;
    }

    /* Which point is showing, so a key press can step from it.  -1 means the
       crosshair is hidden. */
    var at = -1;

    function show(i) {
      if (i < 0) { i = 0; }
      if (i > n - 1) { i = n - 1; }
      at = i;
      var pt = spec.p[i];
      var x = spec.x0 + i * step;
      line.setAttribute('x1', x); line.setAttribute('x2', x);
      line.setAttribute('y1', spec.y0); line.setAttribute('y2', spec.y1);
      dotT.setAttribute('cx', x); dotT.setAttribute('cy', yFor(pt.T));
      if (pt.d === null || pt.d === undefined) {
        dotD.setAttribute('r', 0);
      } else {
        dotD.setAttribute('r', 2.8);
        dotD.setAttribute('cx', x); dotD.setAttribute('cy', yFor(pt.d));
      }
      /* A class, not the html `hidden` attribute.  Two reasons: `hidden` is
         not valid on an SVG <g>, and SVGElement has no `hidden` IDL property
         either -- assigning .hidden would set a JS expando and leave the
         markup untouched. */
      cross.classList.remove('off');
      /* A chart reports only what it plots: the sparkline is temperature
         alone, so its points carry no `d` and no `r` at all and both spans
         are simply left out. */
      out.innerHTML = '<b>' + pt.t + '</b>'
        + '<span class="ro-t">' + pt.T + '°</span>'
        + ((pt.d === null || pt.d === undefined)
             ? '' : '<span class="ro-d">dew ' + pt.d + '°</span>')
        + (pt.r === undefined
             ? '' : '<span class="ro-r">rain ' + pt.r + '%</span>');
      out.hidden = false;
    }

    function readAt(clientX) {
      var box = svg.getBoundingClientRect();
      if (!box.width) { return; }
      /* Drawn in viewBox units and stretched to the css width, so a pointer
         position means nothing until it is scaled back. */
      var scale = svg.viewBox.baseVal.width / box.width;
      show(Math.round(((clientX - box.left) * scale - spec.x0) / step));
    }

    function clear() {
      at = -1;
      cross.classList.add('off');
      out.hidden = true;      /* a real HTMLElement, where .hidden works */
    }

    /* ---- keyboard -----------------------------------------------------
       The chart carries tabindex="0", so it is reachable by Tab; these keys
       then walk the same crosshair the pointer drives.  Nothing about the
       pointer path changes, and no ARIA semantics are touched -- this makes
       the chart OPERABLE without a mouse, which is a different and smaller
       claim than making it accessible to a screen reader. */
    svg.addEventListener('keydown', function (e) {
      var step1 = e.shiftKey ? 6 : 1;
      /* From nothing showing, the first press lands ON an end rather than one
         step past it -- otherwise ArrowRight silently skips the first hour. */
      if (e.key === 'ArrowRight') { show(at < 0 ? 0 : at + step1); }
      else if (e.key === 'ArrowLeft') { show(at < 0 ? n - 1 : at - step1); }
      else if (e.key === 'Home') { show(0); }
      else if (e.key === 'End') { show(n - 1); }
      else if (e.key === 'Escape') { clear(); return; }
      else { return; }
      /* Only once a key is known to be ours: arrow keys must go on scrolling
         the page everywhere else. */
      e.preventDefault();
    });
    /* The ring is for a reader who arrived by keyboard, not for one who
       clicked.  `kbd` is what css keys the outline off; see nws.css. */
    svg.addEventListener('focus', function () {
      svg.classList.toggle('kbd', typing);
    });
    svg.addEventListener('blur', function () {
      svg.classList.remove('kbd');
      clear();
    });

    svg.addEventListener('pointerdown', function (e) { readAt(e.clientX); });
    svg.addEventListener('pointermove', function (e) {
      /* A finger only scrubs while it is down; a mouse always reads. */
      if (e.pointerType === 'mouse' || e.buttons) { readAt(e.clientX); }
    });
    /* A TOUCH pointer fires pointerleave the instant the finger lifts, which
       would wipe the reading the tap just made.  Only a mouse leaving means
       "stop reading"; a finger's reading stands until the next tap elsewhere. */
    svg.addEventListener('pointerleave', function (e) {
      if (e.pointerType === 'mouse') { clear(); }
    });
    svg.addEventListener('pointercancel', clear);
    document.addEventListener('pointerdown', function (e) {
      if (!svg.contains(e.target)) { clear(); }
    });
  }

  function wireCharts() {
    var charts = document.querySelectorAll('svg.chart');
    for (var i = 0; i < charts.length; i++) { wireChart(charts[i]); }
  }

  /* ---- go ------------------------------------------------------------ */

  function start() {
    wireTabs();
    wireCharts();
    tick();
    setInterval(tick, MINUTE);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start);
  } else {
    start();
  }
}());
