## Copyright 2024 John A Kline
## See LICENSE.txt for your rights
#errorCatcher Echo
#encoding UTF-8
    <style>
      .forecastnav {
        overflow: hidden;
      }
      .forecastnav a {
        float: left;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 0px;
        text-decoration: none;
        font-size: 17px;
      }
      .forecastnav a:hover {
        background-color: #ddd;
        color: black;
      }
      .forecastnav a.active {
        background-color: #367ba3;
        color: white;
      }
    </style>
